services:
  bxweb:
    image: docker pull ortussolutions/boxlang:miniserver
    #image: bxserver-test
    environment:
      - BOXLANG_PORT=8080
      - BOXLANG_DEBUG=true
      #- BOXLANG_WEBROOT=/app
      #- BOXLANG_HOST=localhost
      # Path to boxlang.json
      #- BOXLANG_CONFIG=/path/to/boxlang.json
      # Where to store the boxlang home
      - BOXLANG_HOME=/opt/boxlang
      # - JAVA_OPTS=-Xmx512m
      - BOXLANG_MODULES=bx-compat,bx-esapi,bx-mysql
    volumes:
      - ./test:/app
      - ./test/.engine:/opt/boxlang
      - ./build:/root/build
    ports:
      - "8888:8080"
