version: "2.1"

services:
  bxweb:
    image: docker pull ortussolutions/boxlang:miniserver
    environment:
      - BOXLANG_PORT=8080
      - BOXLANG_WEBROOT=/app
      - BOXLANG_DEBUG=false
      - BOXLANG_HOST=localhost
      # Path to boxlang.json
      #- BOXLANG_CONFIG=/path/to/boxlang.json
      # Where to store the boxlang home
      - BOXLANG_HOME=/opt/boxlang
      # - JAVA_OPTS=-Xmx512m
    volumes:
      - ./test:/app
      - ./test/.engine:/opt/boxlang
      - ./build:/root/build
    ports:
      - "8888:8080"
